name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Show host info
        run: |
          uname -a
          cat /etc/os-release
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build container image
        run: |
          IMAGE_NAME=${{secrets.DOCKERHUB_ID}}/ffcord
          docker build -t $IMAGE_NAME -f run.Dockerfile .
          echo
      - name: Push container image
        run: |
          docker push ${{secrets.DOCKERHUB_ID}}/ffcord
          echo "Pushed container image: $IMAGE_NAME"